### ISSUE TITLE
Ensure the same secret name is reused locally and in CI

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1370]
https://github.com/openshift/release/tree/master/projects/azure#test-ci-operator-jobs

We should figure out how to use the same name in both runs, it's annoying to have to rename the secret in the template to test locally.

@openshift/sig-azure 
/kind cleanup

**Comment by bbguimaraes** [comment]
The name of the secret is arbitrary. You can change the value of the `--secret-dir` option passed to `ci-operator` ([e.g.](https://github.com/openshift/release/blob/e0d96e76939fa812510dbb2388c95f73bd868b13/ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml#L18)).

**Comment by mjudeikis** [comment]
I think its just question if prow config mount point?

**Comment by charlesakalugwu** [comment]
@bbguimaraes do you have any more feedback about this?

**Comment by bbguimaraes** [comment]
As @mjudeikis said it is just a matter of changing the volume mount to create a file with the appropriate name, there's nothing special about the file name.

**Comment by kwoodson** [comment]
To elaborate, @bbguimaraes are you stating that we should create a local directory to match the mount name used in the template?

**Comment by bbguimaraes** [comment]
The reverse. Ultimately, the name of the secret in the template and the `basename` of the file passed to ci-operator via `--secret-dir` have to be same.

You can rename the secret in the template if you don't want to have to rename your local directory. Just remember to change the `volumeMount`s to create a file with a `basename` equal to your local directory name, e.g.:

```yaml
      # cluster-launch-e2e-azure.yaml
    - name: cluster-secrets-azure
      secret:
        secretName: foo
      # openshift-openshift-azure-presubmits.yaml
      containers:
      - args:
        …
        - --secret-dir=/usr/local/foo
        command:
        - ci-operator
        …
        volumeMounts:
        …
        - mountPath: /usr/local/foo
          name: cluster-secrets-azure
```
