### ISSUE TITLE
Error starting jobs

### ISSUE THREAD

**Issue by bparees** [openshift/release#1906]
It's a PR against origin-3.11 if it matters: https://github.com/openshift/origin/pull/21226

It is reporting "error starting jenkins jobs" for extended_builds and extended_image_ecosystem.

**Comment by stevekuznetsov** [comment]
If you look at the Prow config, what jobs are being started? Do they exist in aos-cd-jobs or Jenkins?

**Comment by bparees** [comment]
> Do they exist in aos-cd-jobs or Jenkins?

I don't know what this means.  All the jenkins jobs are defined in aos-cd-jobs.

Here's the presubmits for the origin 3.11 branch:

```
  - agent: jenkins
    always_run: false
    branches:
    - release-3.11
    context: ci/openshift-jenkins/extended_image_ecosystem
    labels:
      master: ci.openshift.redhat.com
    name: test_pull_request_origin_extended_image_ecosystem-release-3.11
    rerun_command: /test extended_image_ecosystem
    run_if_changed: ^(test/extended/image_ecosystem)|^(examples/db-templates)|^(examples/quickstarts)|^(examples/image-streams)|^(examples/jenkins)|^(vendor/github.com/openshift/source-to-image)|^(vendor/github.com/openshift/imagebuilder)
    trigger: ((?m)^/test extended_image_ecosystem,?(\s+|$))

```

```
  - agent: jenkins
    always_run: false
    branches:
    - release-3.11
    context: ci/openshift-jenkins/extended_builds
    labels:
      master: ci.openshift.redhat.com
    name: test_pull_request_origin_extended_builds-release-3.11
    rerun_command: /test extended_builds
    run_if_changed: ^(pkg/oc/cli/startbuild/startbuild.go)|^(pkg/build)|^(pkg/cmd/infra/builder)|^(test/extended/builds)|^(test/extended/testdata/builds)|^(vendor/github.com/openshift/source-to-image)|^(vendor/github.com/openshift/imagebuilder)
    trigger: ((?m)^/test extended_builds,?(\s+|$))
```
