### ISSUE TITLE
local development caches images

### ISSUE THREAD

**Issue by mjudeikis** [openshift/release#2055]
Azure OSA running our node builds locally using syntax:
```
docker run --rm -it --env DEPLOY_OS=rhel7 --env OPENSHIFT_RELEASE="3.11" --env AZURE_OREG_URL="registry.access.redhat.com/openshift3/ose-\${component}:\${version}" --volume $HOME/.kube/config:/root/.kube/config --volume /home/mjudeiki/go/src/github.com/openshift/release:/release registry.svc.ci.openshift.org/ci/ci-operator:latest --config /release/ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11.yaml --git-ref=mjudeikis/openshift-azure@osa.311.node.build --namespace=${CI_OPERATOR_NAMESPACE} --template /release/ci-operator/templates/openshift/openshift-azure/build-node-image.yaml --secret-dir /release/cluster/test-deploy/azure/ --target build-node-image
```

Which uses ansible-3.11 ref so we should get those images into our project. And we get them:
```
- annotations: null
    from:
      kind: ImageStreamImage
      name: origin-v3.11@sha256:dbd4a17599cce9759587c38e891e7cc2ea78e843ea3d9983db6de8acc16cf83d
      namespace: openshift
    generation: 1
    importPolicy: {}
    name: logging-elasticsearch
    referencePolicy:
      type: Source
  - annotations: null
```

The template is using reference: 
```
- name: IMAGE_ANSIBLE
  required: true
```

But I get the cached image from the node, where I can see I use the wrong image:
```
TASK [openshift_version : debug] ***********************************************
Friday 02 November 2018  13:39:27 +0000 (0:00:00.064)       0:04:48.594 ******* 
ok: [157.56.183.204] => {
    "msg": "openshift_pkg_version was not defined. Falling back to -3.10"
}
```

and if I rerun the same command, I get scheduled to different node I get the right image. I imagine "always pull" should be added somewhere :) 

cc: @charlesakalugwu @kargakis @stevekuznetsov @bbguimaraes
