### ISSUE TITLE
help getting jenkins e2e back on track

### ISSUE THREAD

**Issue by gabemontero** [openshift/release#2234]
/kind question

/area test-execution

So until yesterday, it had been 3 weeks since we last tried (and successfully ran) the jenkins e2e.
The jenkins e2e no longer worked we we tried again yesterday.

The failure was that the openshift/jenkins repo content we expected to pick via augmenting the test image with https://github.com/openshift/release/blob/master/ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml#L13-L20 was no longer present.... that image build is suppose to go to `jenkins-e2e-tests`.

I see it consistently working:

```
2018/11/27 15:22:57 Build jenkins-e2e-tests succeeded after 42s
2018/11/27 15:22:57 Tagging jenkins-e2e-tests into ci-op-mflkh1jq/stable:tests
```

Those lines for reference:
```
images:
- from: cluster-tests
  inputs:
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/jenkins/test-e2e/.
  optional: true
  to: jenkins-e2e-tests
```

The content being missing caused https://github.com/openshift/release/blob/master/ci-operator/templates/cluster-launch-e2e-openshift-jenkins.yaml#L135 to fail, as the `PREPARE_COMMAND` was not present.

So after some conversation between @bparees @stevekuznetsov and myself and reading of https://github.com/openshift/ci-operator/blob/master/TEMPLATES.md we changed https://github.com/openshift/release/blob/master/ci-operator/templates/cluster-launch-e2e-openshift-jenkins.yaml#L69 from `${IMAGE_TESTS}` to `${IMAGE_JENKINS_E2E_TESTS}`.

However, I manage to catch the e2e job in progress on api.ci, and see that the `prepare` container failed with:

```
    state:
      waiting:
        message: 'Failed to apply default image tag "${IMAGE_JENKINS_E2E_TESTS}":
          couldn''t parse image reference "${IMAGE_JENKINS_E2E_TESTS}": invalid reference
          format: repository name must be lowercase'
        reason: InvalidImageName
```

So this and the image build output (tagging as `stable:tests`) had me going back to our ci-operator config.

Getting tagged as `stable:tests` I believe is occurring because of this:

https://github.com/openshift/release/blob/master/ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml#L79-L85

Those lines for reference:
```
- output_image_tag_step:
    from: jenkins-e2e-tests
    optional: true
    to:
      as: tests
      name: stable
      tag: tests
```

So my guess is that the `tests` tag somehow was no longer a valid option in changes that occurred in ci-operator/release/ etc. between yesterday and 3 weeks ago.

And that we need to change that `output_image_tag_step` somehow.  I could not discern from https://github.com/openshift/ci-operator/blob/master/CONFIGURATION.md and some of the other doc in ci-operator with certainty what that would be.

- get rid of it? ... the images stanza above is sufficient?
- change the tag and/or as fields to jenkins-e2e-tests
- replace `output_image_tag_step` with something else?

help please
