### ISSUE TITLE
Problem building image for new component - not enough info to troubleshoot

### ISSUE THREAD

**Issue by rogbas** [openshift/release#3091]
/kind bug

## What did you expect to happen?
A new ci job configuration was added for a new operator (**openshift/dedicated-admin-operator**), that will be used by the **Managed Openshift services (Dedicated/Online/Pro)**. As part of the automatic PR checks, the image building process is failing.
PR: https://github.com/openshift/release/pull/3047

## Current config file (after changes suggested on the PR):

```YAML
base_images:
  base:
    name: '4.0'
    namespace: ocp
    tag: base
binary_build_commands: make build
canonical_go_repository: github.com/openshift/dedicated-admin-operator
images:
- from: base
  to: dedicated-admin-operator
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: '4.0'
  namespace: ocp
build_root:
  project_image:
    dockerfile_path: build/Dockerfile

```

The expected was:
* Operator to be built based on the parameter **binary_build_commands: make build**
* Container built from the binary generated above, based on Dockerfile specified on **dockerfile_path: build/Dockerfile**
* Image pushed into repository 

## What happened?
The image build process fails (link with log below) without enough information to troubleshoot what happened.
log: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/3047/rehearse-3047-pull-ci-openshift-dedicated-admin-operator-master-images/5

## How can the error be reproduced?
Just triggering the build again. I can push again to generate some fresh data if you need it.

@jewzaam @aaronlevy
