### ISSUE TITLE
templates: rehearsing e2e templates does not work

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#5989]
I add a new configuration for a repo:

```yaml
- artifact_dir: /tmp/artifacts
  as: e2e-aws-build01
  commands: TEST_SUITE=openshift/conformance/parallel run-tests
  openshift_installer:
    cluster_profile: aws
```

The rehearsal for my new e2e [fails](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5987/rehearse-5987-pull-ci-openshift-ci-secret-mirroring-controller-master-e2e-aws-build01/1#1:build-log.txt%3A19):

```
error: could not run steps: step e2e-aws-build01 failed: template e2e-aws-build01 has required parameter RELEASE_IMAGE_LATEST which is not defined
```

/assign @smarterclayton 
/cc @sallyom @hongkailiu
