### ISSUE TITLE
[plank]Failed to report ProwJob status

### ISSUE THREAD

**Issue by hongkailiu** [openshift/release#6114]
```
{
 insertId: "1h0fgs9g1m79qx2"  
 jsonPayload: {
  component: "plank"   
  error: "error setting status: status code 404 not one of [201], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}"   
  event-GUID: "f9ed0fda-1082-11ea-8f2c-7f47c9ed93f7"   
  file: "prow/plank/controller.go:282"   
  func: "k8s.io/test-infra/prow/plank.(*Controller).Sync"   
  job: "branch-ci-redhat-cop-org-master-sync"   
  level: "warning"   
  msg: "Failed to report ProwJob status"   
  name: "fa2cc27f-1082-11ea-a3c0-0a58ac10a4f6"   
  type: "postsubmit"   
 }
 labels: {
  compute.googleapis.com/resource_name: "fluentd-gcp-v2.1-qgbwh"   
 }
 logName: "projects/openshift-ci-infra/logs/kubernetes.plank-57b89d8968-kvtwh_ci_plank"  
 receiveTimestamp: "2019-11-26T19:31:35.679773424Z"  
 resource: {
  labels: {
   instance_id: "6384852698872031134"    
   project_id: "openshift-ci-infra"    
   zone: "us-east1-c"    
  }
  type: "gce_instance"   
 }
 timestamp: "2019-11-26T19:31:33Z"  
}
```

**Comment by stevekuznetsov** [comment]
We should dig into this, what is not found? The SHA to report status for?

**Comment by hongkailiu** [comment]
Job url: 
https://prow.svc.ci.openshift.org/prowjob?prowjob=fa2cc27f-1082-11ea-a3c0-0a58ac10a4f6

```
  refs:
    base_link: https://github.com/redhat-cop/org/compare/c37ea2f35b75...d0257b48e69a
    base_ref: master
    base_sha: d0257b48e69a491b21cbacdc7945a1e5e32ee8f2
    org: redhat-cop
    repo: org
  report: true
```
