### ISSUE TITLE
networking issues related to history endpoint in Tide

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6467]
[14:53 CET Writing JSON history response (error=write tcp 172.16.86.157:8888->172.16.89.122:47984: write: connection reset by peer)](https://console.cloud.google.com/logs/viewer?authuser=1&project=openshift-ci-infra&folder&organizationId&minLogLevel=0&expandAll=false&timestamp=2019-12-18T13%3A24%3A42.003000000Z&customFacets=jsonPayload.msg&limitCustomFacetWidth=false&dateRangeStart=2019-12-18T12%3A54%3A36.314Z&dateRangeEnd=2019-12-18T13%3A54%3A36.314Z&interval=PT1H&resource=gce_instance&scrollTimestamp=2019-12-18T13%3A53%3A26.000000000Z&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Aresource.labels.instance_id%3D%227761477983110761797%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Atimestamp%3D%222019-12-18T13%3A53%3A26.000000000Z%22%0AinsertId%3D%221xy2gsf7ig8cb%22)
```yaml
{
  component: "tide",
  error: "write tcp 172.16.86.157:8888->172.16.89.122:47984: write: connection reset by peer",
  file: "prow/tide/history/history.go:177",
  func: "k8s.io/test-infra/prow/tide/history.(*History).ServeHTTP",
  level: "error",
  msg: "Writing JSON history response.",
 }
```
[14:53 CET Updating history. (read tcp 172.16.89.122:47984->172.30.217.234:80: read: connection reset by peer)](https://console.cloud.google.com/logs/viewer?authuser=1&project=openshift-ci-infra&folder&organizationId&minLogLevel=0&expandAll=false&timestamp=2019-12-18T13%3A24%3A42.003000000Z&customFacets=jsonPayload.msg&limitCustomFacetWidth=false&dateRangeStart=2019-12-18T12%3A54%3A36.314Z&dateRangeEnd=2019-12-18T13%3A54%3A36.314Z&interval=PT1H&resource=gce_instance&scrollTimestamp=2019-12-18T13%3A53%3A26.000000000Z&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%223461846773534648075%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Atimestamp%3D%222019-12-18T13%3A53%3A26.000000000Z%22%0AinsertId%3D%221pvzr58f7h7gyn%22):
```yaml
{
  agent: "tide",
  component: "deck",
  error: "[read tcp 172.16.89.122:47984->172.30.217.234:80: read: connection reset by peer]",
  file: "prow/cmd/deck/tide.go:84",
  func: "main.(*tideAgent).start.func2",
  level: "error",
  msg: "Updating history."
 }
```
[14:12 CET error executing template job-history.html (write tcp 172.16.89.122:8080->172.16.8.83:55206: write: broken pipe)](https://console.cloud.google.com/logs/viewer?authuser=1&project=openshift-ci-infra&folder&organizationId&minLogLevel=0&expandAll=false&timestamp=2019-12-18T13%3A24%3A42.003000000Z&customFacets=jsonPayload.msg&limitCustomFacetWidth=false&dateRangeStart=2019-12-18T12%3A54%3A36.314Z&dateRangeEnd=2019-12-18T13%3A54%3A36.314Z&interval=PT1H&resource=gce_instance&scrollTimestamp=2019-12-18T13%3A53%3A26.000000000Z&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%223461846773534648075%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Atimestamp%3D%222019-12-18T13%3A12%3A42.000000000Z%22%0AinsertId%3D%22148mewof5g74lt%22):
```yaml
{
  component: "deck",
  error: "write tcp 172.16.89.122:8080->172.16.8.83:55206: write: broken pipe",
  file: "prow/cmd/deck/templates.go:95",
  func: "main.handleSimpleTemplate.func1",
  level: "error",
  msg: "error executing template job-history.html"   
 }
```

/area triage
