### ISSUE TITLE
Prow metrics are not scrapped by prometheus

### ISSUE THREAD

**Issue by kargakis** [openshift/release#759]
Unclear yet why

@stevekuznetsov @smarterclayton

**Comment by kargakis** [comment]
Seems Prometheus is configured to scrape only infra components; @smarterclayton why is that the case?

**Comment by kargakis** [comment]
```yaml
    # Scrape config for service endpoints.
    #
    # The relabeling allows the actual service scrape endpoint to be configured
    # via the following annotations:
    #
    # * `prometheus.io/scrape`: Only scrape services that have a value of `true`
    # * `prometheus.io/scheme`: If the metrics endpoint is secured then you will need
    # to set this to `https` & most likely set the `tls_config` of the scrape config.
    # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
    # * `prometheus.io/port`: If the metrics are exposed on a different port to the
    # service then set this appropriately.
    - job_name: 'kubernetes-service-endpoints'

      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        # TODO: this should be per target
        insecure_skip_verify: true

      kubernetes_sd_configs:
      - role: endpoints

      relabel_configs:
      # only scrape infrastructure components
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: 'default|logging|metrics|kube-.+|openshift|openshift-.+'
```
