### ISSUE TITLE
prow job failed with all tests passed: Job cannot be started: pods XXX already exists

### ISSUE THREAD

**Issue by hongkailiu** [openshift/release#8374]
https://coreos.slack.com/archives/CBN38N3MW/p1587070369289300

```
build_id: "953"
  completionTime: "2020-04-16T20:42:07Z"
  description: 'Job cannot be started: pods "546cb4f9-8022-11ea-9883-0a58ac10fbe1"
    already exists'
  pendingTime: "2020-04-16T20:39:33Z"
  pod_name: 546cb4f9-8022-11ea-9883-0a58ac10fbe1
  prev_report_states:
    gcsk8sreporter: error
    gcsreporter: error
    github-reporter: error
  startTime: "2020-04-16T20:39:12Z"
  state: error
```
